version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: dreamcatcher-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: dreamcatcher_db
      MYSQL_USER: db_user_dc
      MYSQL_PASSWORD: please_let_us_alone_1990
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mariadb_data:
