# DreamCatcher/.github/workflows/deploy_prod.yml
# Deploying branch 'master' to www.dreamcatcher.galister.ch
#     runner runs on webt.int.galister.ch

name: Deploy prod

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64, m245, webt.int.galister.ch, debian]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Restart nginx
        run: sudo systemctl restart nginx
