# DreamCatcher/.github/workflows/deploy.yml
run-name: Deploy to www.dreamcatcher.galister.ch

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64, m245, webt.int.galister.ch, debian]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Deploy to webt.int.galister.ch
      run: |
        git pull
        git checkout master
        sudo systemctl restart nginx