# DreamCatcher/.github/workflows/deploy_dev.yml
# Deploying branch 'dev' to www.dreamcatcher.galister.ch
#     runner runs on webt.int.galister.ch
#     Just a test entry

name: Deploy dev

on:
  workflow_run:
    workflows: ["Install packages before deployment"]
    types:
      - completed

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64, m245, webt.int.galister.ch, debian]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Build static files of Angular project
        run: cd Frontend && npm install && ng build --prod

      - name: Show files in dist
        run: cd dist/DreamCatcherFrontend/ && ls -lsa

      - name: Restart nginx
        run: sudo systemctl restart nginx
  