# DreamCatcher/.github/workflows/deploy.yml
name: Deploy prod (master) to www.dreamcatcher.galister.ch

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64, m245, webt.int.galister.ch, debian]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0

      - name: Checkout master and pull
        run: |
          git checkout master
          git pull

      - name: Restart nginx
        run: sudo systemctl restart nginx
