# DreamCatcher/.github/workflows/dev.yml
# Second workflow for deploying dev
name: Deploy dev to www.dreamcatcher.galister.ch

on:
  pull_request:
    types:
      - closed
    branches:
      - dev

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64, m245, webt.int.galister.ch, debian]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Checkout dev and pull
        run: |
          git checkout dev
          git pull

      - name: Restart nginx
        run: sudo systemctl restart nginx
